### ISSUE TITLE
Azure Template Vnet Failure [Ckp SMS & GW]

### ISSUE THREAD

**Issue by rcarrata** [CheckPointSW/CloudGuardIaaS#56]
Hi,

Deploying the Azure Ckp SMS and Gateway in Azure platform with the  [`mainTemplate.json template`](https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-single/mainTemplate.json) I received an error:

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidContentLink\",\r\n \"message\": \"Unable to download deployment content from 'https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates/vnet-1-subnet-existing.json'. The tracking Id is 'xxxx-xxxx-xxxx-xxxx-xxxx'. Please see https://aka.ms/arm-deploy for usage details.\"\r\n }\r\n}"}]}
```

This is because in [this line](https://github.com/CheckPointSW/CloudGuardIaaS/blob/master/azure/templates/marketplace-single/mainTemplate.json#L346) is referring to a template that is moved to other location:

This template is no longer reachable:  https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates/vnet-1-subnet-existing.json 

and its moved from  

```CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates``` 

to 

```CheckPointSW/CloudGuardIaaS/blob/master/azure/templates/nestedtemplates/vnet-1-subnet-existing.json```

For this reason this template is producing an error in the download of one of the dependencies (vnet-1-subnet-existing.json).

![4](https://user-images.githubusercontent.com/5543225/94459263-65977600-01b7-11eb-8602-cd1969407e7e.png)

Can you please help us to fix the link in order to succeed in the installation?

Thanks in advance for you help!

**Comment by chkp-romanka** [comment]
@rcarrata 
Hello Roberto,
Just tried to deploy the solutions and it works as expected for me
Can you elaborate how exactly have you tried to deploy the solution? Via "Templates" service in Azure portal or PowerShell?
By saying Chkp SMS + GW deployment do you mean Standalone? Or you have tried to deploy both solution separately(Chkp SMS and GW)  
If you deployed the solution via "Templates" service what _artifactsLocation URL did you use?

Thanks,
Roman

**Comment by rcarrata** [comment]
Hi @chkp-romanka, thanks for your quick answer and for the update.

I'm installing the R80.30 version of the SMS and the GW  from an Ansible Playbook using the azure_rm_deployment module (both separated in two different playbooks) with the latest version from ansible 2.9.10).

The playbook for SMS is using the template from: https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/mainTemplate.json and I'm adding some parameters that they need to work:

```
    - name: Create resource group for SMS
      azure_rm_resourcegroup:
        name: Testing_VM_rg_chkp_smsansible_fest
        location: francecentral

    - name: Deploy SMS on azure
      ignore_errors: True
      azure_rm_deployment:
        state: present
        location: francecentral
        resource_group_name: Testing_VM_rg_chkp_smsansible_fest
        parameters:
          location:
            value: francecentral
          cloudGuardVersion:
            value: R80.30 - Bring Your Own License
          adminPassword:
            value: xxxxxx
          authenticationType:
            value: password
          vmName:
            value: chkpsmsansiblefest
          vmSize:
            value: Standard_D3_v2
          virtualNetworkName:
            value: Testing_VM_vnet_ansible_fest_francecentral
          Subnet1Name:
            value: Testing_VM_snet_internal_ansible_fest_francecentral
          Subnet1Prefix:
            value: 11.0.1.0/24
          Subnet1StartAddress:
            value: 11.0.1.6
          vnetNewOrExisting:
            value: existing
          virtualNetworkExistingRGName:
            value: Testing_VM_rg_ansible_fest
          managementGUIClientNetwork:
            value: 0.0.0.0/0
          installationType:
            value: management
          allowDownloadFromUploadToCheckPoint:
            value: 'true'
          additionalDiskSizeGB:
            value: 0
          diskType:
            value: Standard_LRS
          sourceImageVhdUri:
            value: noCustomUri
        template_link: https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/mainTemplate.json
```

The azure rm template executed from Ansible works perfectly until try to download one file that is setting as dependency: 

```
{
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
....
    "msg": "Deployment failed with status code: 200 and message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
}
```

If I check in the Azure console I see the error:

![6](https://user-images.githubusercontent.com/5543225/94535935-6f19f000-0242-11eb-971e-9f4aa2650c2b.png)

with the networkExistingSetup as a BadRequest.

This networkExistingSetup step outputs with an error:

```
{
    "error": {
        "code": "InvalidContentLink",
        "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates/vnet-1-subnet-existing.json'. The tracking Id is '2c79911b-4c48-421d-a189-3a84e8f41ef6'. Please see https://aka.ms/arm-deploy for usage details."
    }
}
```

The main template tried to download a dependency vnet-1-subnet-existing.json that is moved to another location (see that the link that is trying to download is no longer reachable in this path, and outputs an 404 when you try to download manually).

For this reason I think that the maintemplate needs to point to a proper path (without the marketplace-management), instead of the incorrect one:

```https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates/vnet-1-subnet-existing.json```

to

```https://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/nestedtemplates/vnet-1-subnet-existing.json```

The outputhttps://raw.githubusercontent.com/CheckPointSW/CloudGuardIaaS/master/azure/templates/marketplace-management/nestedtemplates/vnet-1-subnet-existing.json

Thanks,

Roberto
